### ISSUE TITLE
Create images with multiple versions

### ISSUE THREAD

**Issue by joelzamboni** [wearewebera/image-nodejs#3]
Install NVM on the base image and keep at least the last and the current LTS version - which today is Node 18 and Node 20

```
webera/nodejs:18
webera/nodejs:20
```

![image](https://github.com/wearewebera/image-nodejs/assets/4838831/3ec8a756-6a11-4172-aee9-069cb985761f)

**Comment by joelzamboni** [comment]
https://tecadmin.net/how-to-install-nvm-on-ubuntu-22-04/

https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-22-04

**Comment by SamuelSPatrocinio** [comment]
Installed NVM in the base image and now I'm trying to figure out a way to source the `nvm.sh` file across `RUN` calls in the dockerfile since a new shell is called everytime this keyword is executed and also a new layer is created, thus the `nvm.sh` is not persited and a `command not found error is thrown`

**Comment by mauriciopeixoto3** [comment]
@joelzamboni can you check this task, please?

**Comment by SamuelSPatrocinio** [comment]
NVM with two separate node images wouldn't make sense I guess, and one node image with the two versions would be too big as discussed in the daily meeting today. Thus, I created two independent images with the tags webera/nodejs:18 and webera/nodejs:20. The main github branch corresponds to node 20 and there is another branch that represents node 18.

**Comment by joelzamboni** [comment]
@SamuelSPatrocinio the base node image can have the default npm and node that comes with the distro, you can also add the NVM to the base one, and then build the two other images using an argument to which version can be installed. What do you think?

**Comment by mauriciopeixoto3** [comment]
Already closed.
